/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as PrescriptionsIndexImport } from './routes/prescriptions/index'
import { Route as PrescriptionsIdImport } from './routes/prescriptions/$id'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PrescriptionsIndexRoute = PrescriptionsIndexImport.update({
  id: '/prescriptions/',
  path: '/prescriptions/',
  getParentRoute: () => rootRoute,
} as any)

const PrescriptionsIdRoute = PrescriptionsIdImport.update({
  id: '/prescriptions/$id',
  path: '/prescriptions/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/prescriptions/$id': {
      id: '/prescriptions/$id'
      path: '/prescriptions/$id'
      fullPath: '/prescriptions/$id'
      preLoaderRoute: typeof PrescriptionsIdImport
      parentRoute: typeof rootRoute
    }
    '/prescriptions/': {
      id: '/prescriptions/'
      path: '/prescriptions'
      fullPath: '/prescriptions'
      preLoaderRoute: typeof PrescriptionsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/prescriptions/$id': typeof PrescriptionsIdRoute
  '/prescriptions': typeof PrescriptionsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/prescriptions/$id': typeof PrescriptionsIdRoute
  '/prescriptions': typeof PrescriptionsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/prescriptions/$id': typeof PrescriptionsIdRoute
  '/prescriptions/': typeof PrescriptionsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/prescriptions/$id' | '/prescriptions'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/prescriptions/$id' | '/prescriptions'
  id: '__root__' | '/' | '/about' | '/prescriptions/$id' | '/prescriptions/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  PrescriptionsIdRoute: typeof PrescriptionsIdRoute
  PrescriptionsIndexRoute: typeof PrescriptionsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  PrescriptionsIdRoute: PrescriptionsIdRoute,
  PrescriptionsIndexRoute: PrescriptionsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/prescriptions/$id",
        "/prescriptions/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/prescriptions/$id": {
      "filePath": "prescriptions/$id.tsx"
    },
    "/prescriptions/": {
      "filePath": "prescriptions/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
