root = "."
testdata_dir = "testdata"
tmp_dir = "./tmp"

[build]
  bin = "./tmp/main"
  cmd = "go build -o ./tmp/main ./cmd/api"
  delay = 1000
  include_dir = ["cmd", "internal", "handler", "middleware", "service", "database"]
  include_ext = ["go"]
  kill_delay = "2s"
  log = "build-errors.log"
  poll = true
  poll_interval = 20  # Faster polling
  send_interrupt = false

[misc]
  clean_on_exit = false 

[screen]
  clear_on_rebuild = false